#!/usr/bin/env bash
# setup.sh — first-time project setup for personal-finance
# Generated by python-project-template · https://github.com/mcintalmo/python-project-template
#
# Usage: bash setup.sh [--skip-checks] [--skip-push]
#
# Windows users: run this inside WSL or Git Bash.

set -euo pipefail

# ── Options ──────────────────────────────────────────────────────────────────
SKIP_CHECKS=false
SKIP_PUSH=false
for arg in "$@"; do
  case $arg in
    --skip-checks) SKIP_CHECKS=true ;;
    --skip-push)   SKIP_PUSH=true ;;
  esac
done

# ── Colours ───────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
  RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
  BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
else
  RED=''; GREEN=''; YELLOW=''; BLUE=''; BOLD=''; NC=''
fi

step()  { echo -e "\n${BLUE}${BOLD}▶ $*${NC}"; }
ok()    { echo -e "${GREEN}✓ $*${NC}"; }
warn()  { echo -e "${YELLOW}⚠ $*${NC}"; }
fail()  { echo -e "${RED}✗ $*${NC}"; exit 1; }
info()  { echo -e "  $*"; }

# ── Detect OS ─────────────────────────────────────────────────────────────────
case "$(uname -s)" in
  Darwin*)  OS=macOS ;;
  Linux*)   OS=Linux ;;
  CYGWIN*|MINGW*|MSYS*) OS=Windows ;;
  *)        OS=Unknown ;;
esac

echo -e "\n${BOLD}Setting up personal-finance on $OS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── 1. Install uv ─────────────────────────────────────────────────────────────
step "Checking uv"
if command -v uv &>/dev/null; then
  ok "uv $(uv --version | awk '{print $2}') already installed"
else
  info "Installing uv..."
  if [[ "$OS" == "macOS" || "$OS" == "Linux" ]]; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
    # Reload PATH so uv is available in this session
    export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
    source "$HOME/.local/bin/env" 2>/dev/null || true
  elif [[ "$OS" == "Windows" ]]; then
    fail "Windows detected — please install uv manually: https://docs.astral.sh/uv/getting-started/installation/#windows"
  fi
  command -v uv &>/dev/null || fail "uv install failed — please install manually: https://docs.astral.sh/uv/"
  ok "uv installed ($(uv --version | awk '{print $2}'))"
fi

# ── 2. Install copier ─────────────────────────────────────────────────────────
step "Checking copier"
if uv tool list 2>/dev/null | grep -q "^copier"; then
  ok "copier already installed"
elif command -v copier &>/dev/null; then
  ok "copier found at $(command -v copier)"
else
  info "Installing copier via uv tool..."
  uv tool install copier
  ok "copier installed"
fi

# ── 3. Install Python dependencies ────────────────────────────────────────────
step "Installing dependencies (uv sync)"
uv sync
ok "Dependencies installed"

# ── 4. Install pre-commit hooks ───────────────────────────────────────────────
step "Installing pre-commit hooks"
uv run pre-commit install
ok "pre-commit hooks installed (runs ruff + ty on every commit)"

# ── 5. Set up local environment ───────────────────────────────────────────────
step "Setting up local environment"
if [ -f .env.local ]; then
  warn ".env.local already exists — skipping copy"
elif [ -f .env.example ]; then
  cp .env.example .env.local
  ok "Copied .env.example → .env.local"
  warn "Edit .env.local with your development values before running the project"
else
  warn ".env.example not found — skipping"
fi

# ── 6. Run checks ─────────────────────────────────────────────────────────────
if [[ "$SKIP_CHECKS" == "false" ]]; then
  step "Running checks (ruff → ty → pytest)"

  CHECKS_PASSED=true

  info "ruff format --check ..."
  if ! uv run ruff format --check . 2>&1; then
    warn "Formatting issues found — run: uv run ruff format ."
    CHECKS_PASSED=false
  fi

  info "ruff check ..."
  if ! uv run ruff check . 2>&1; then
    warn "Lint issues found — run: uv run ruff check --fix ."
    CHECKS_PASSED=false
  fi

  info "ty check ..."
  if ! uv run ty check src/ 2>&1; then
    warn "Type errors found — fix before committing"
    CHECKS_PASSED=false
  fi

  info "pytest ..."
  if ! uv run pytest 2>&1; then
    warn "Tests failed — fix before committing"
    CHECKS_PASSED=false
  fi

  if [[ "$CHECKS_PASSED" == "true" ]]; then
    ok "All checks passed"
  else
    warn "Some checks failed — review output above, then re-run or use --skip-checks"
    read -r -p "  Continue with git setup anyway? [y/N] " reply
    [[ "$reply" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }
  fi
else
  warn "Skipping checks (--skip-checks)"
fi

# ── 7. Git setup ──────────────────────────────────────────────────────────────
step "Git setup"

if git rev-parse --git-dir &>/dev/null 2>&1; then
  warn "Already a git repository — skipping init"
else
  git init -b main
  ok "Initialised git repository (branch: main)"
fi

# Configure git identity if not set
if ! git config user.name &>/dev/null; then
  read -r -p "  Git user name: " GIT_NAME
  git config user.name "$GIT_NAME"
fi
if ! git config user.email &>/dev/null; then
  read -r -p "  Git user email: " GIT_EMAIL
  git config user.email "$GIT_EMAIL"
fi

git add .
ok "Staged all files"

if git diff --cached --quiet; then
  warn "Nothing to commit (working tree clean)"
else
  git commit -m "chore: initial project from python-project-template"
  ok "Initial commit created"
fi

# ── 8. Push to GitHub ─────────────────────────────────────────────────────────
if [[ "$SKIP_PUSH" == "false" ]]; then
  step "Push to GitHub"

  DEFAULT_REMOTE="https://github.com/mcintalmo/personal_finance.git"

  if git remote get-url origin &>/dev/null 2>&1; then
    CURRENT_REMOTE="$(git remote get-url origin)"
    ok "Remote 'origin' already set: $CURRENT_REMOTE"
  else
    echo -e "  Default remote: ${BOLD}$DEFAULT_REMOTE${NC}"
    read -r -p "  GitHub remote URL [press Enter to use default]: " REMOTE_INPUT
    REMOTE="${REMOTE_INPUT:-$DEFAULT_REMOTE}"
    git remote add origin "$REMOTE"
    ok "Remote added: $REMOTE"
  fi

  git branch -M main

  if command -v gh &>/dev/null; then
    REPO_NAME="$(git remote get-url origin | sed 's|.*github.com[:/]\(.*\)\.git|\1|')"
    if ! gh repo view "$REPO_NAME" &>/dev/null 2>&1; then
      info "Creating GitHub repo $REPO_NAME via gh CLI..."
      gh repo create "$REPO_NAME" --public \
        --description "Personal finance and budget management app, using data pipelining, machine learning, AI, and data visualization to make where money is going immediately intuitive." \
        --source . --push
      ok "Repo created and pushed"
    else
      git push -u origin main
      ok "Pushed to $REPO_NAME"
    fi
  else
    warn "gh CLI not found — pushing to existing remote"
    info "(To create the repo first: gh repo create mcintalmo/personal_finance --public)"
    git push -u origin main && ok "Pushed to origin/main" \
      || warn "Push failed — ensure the GitHub repo exists and you have write access"
  fi
else
  warn "Skipping push (--skip-push)"
fi

# ── 9. Claude plugins (manual) ────────────────────────────────────────────────
step "Claude Code plugins (manual step)"
echo ""
echo -e "  Run these once inside ${BOLD}Claude Code${NC} — they apply across all your projects:"
echo ""
echo -e "  ${BOLD}/plugin install security-guidance@claude-plugins-official${NC}"
echo -e "    Real-time security review on every file edit and commit."
echo ""
echo -e "  ${BOLD}/plugin install skill-creator@claude-plugins-official${NC}"
echo -e "    Build and evaluate new project skills."
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}${BOLD}Setup complete!${NC}"
echo ""
echo -e "  Next steps:"
echo -e "  1. Set GITHUB_TOKEN in ~/.zshrc or .env.local (for MCP server)"
echo -e "  2. Edit .env.local with your dev values"
echo -e "  3. Open Claude Code and try: ${BOLD}/run-checks${NC}"
echo -e "  4. Read AGENTS.md to see the AI coding conventions"
echo ""
